# Generated by Django 5.1.6 on 2025-03-18 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderpizza',
            name='toppings',
        ),
        migrations.AddField(
            model_name='orderpizza',
            name='topping_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topping_1', to='accounts.topping'),
        ),
        migrations.AddField(
            model_name='orderpizza',
            name='topping_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topping_2', to='accounts.topping'),
        ),
        migrations.AddField(
            model_name='orderpizza',
            name='topping_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topping_3', to='accounts.topping'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_summary',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
