# Generated by Django 5.1.6 on 2025-03-18 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_orderpizza_toppings_orderpizza_topping_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(blank=True, help_text='Full name for guest orders', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='restaurant_location',
            field=models.ForeignKey(blank=True, help_text='Select the store fulfilling this order.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.restaurantlocation'),
        ),
        migrations.AlterField(
            model_name='orderpizza',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderpizza_set', to='accounts.order'),
        ),
    ]
