# Generated by Django 5.1.6 on 2025-03-18 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_order_restaurant_address_order_restaurant_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='card_expiry_date',
            field=models.CharField(blank=True, help_text='MM/YYYY format.', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='card_last_four',
            field=models.CharField(blank=True, help_text='Last 4 digits of the card number.', max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='card_type',
            field=models.CharField(blank=True, choices=[('Visa', 'Visa'), ('MasterCard', 'MasterCard'), ('American Express', 'American Express'), ('Discover', 'Discover'), ('Other', 'Other')], help_text='Select the type of credit card used.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='paypal_email',
            field=models.EmailField(blank=True, help_text='PayPal email if PayPal was used.', max_length=254, null=True),
        ),
        migrations.AlterModelTable(
            name='order',
            table='accounts_order',
        ),
    ]
