# Generated by Django 5.1.6 on 2025-03-19 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_restaurantlocation_zip_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='dessert',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='drink',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pizza',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wing',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
