# Generated by Django 5.1.6 on 2025-03-19 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_dessert_image_drink_image_pizza_image_wing_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='image',
            field=models.ImageField(default='images/default_pizza.jpg', upload_to='images/pizzas/'),
        ),
    ]
