# Generated by Django 5.1.6 on 2025-04-03 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_alter_pizza_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pizza",
            name="toppings",
        ),
        migrations.AlterField(
            model_name="orderpizza",
            name="size",
            field=models.CharField(
                choices=[
                    ("small", "Small"),
                    ("medium", "Medium"),
                    ("large", "Large"),
                    ("extra_large", "Extra Large"),
                ],
                default="Small",
                max_length=15,
            ),
        ),
    ]
