# Generated by Django 5.1.6 on 2025-03-18 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_order_card_expiry_date_order_card_last_four_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantlocation',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
